### ISSUE TITLE
[MVP] Agent 

### ISSUE THREAD

**Issue by alexandrebrg** [isok-io/isok#20]
## Agent

```toml
# /etc/isok/config.toml
main_broker = "http://broker-eu-fr-par1"
fallback_brokers = ["http://broker-eu-uk-lon1", "http://fallback_2"]

# Must be sent with every message
zone = ""
region = ""

# Max number of message that can be bufferized, if full, send to broker
batch = 100
# Maximum interval to which we send a batch
batch_interval = 10

[check_config_adapter]
name = "file"
path = "/etc/isok/checks.toml"
```

```toml
# /etc/isok/checks.toml
[checks.id1]
pretty_name = "60s endpoint check"
type = "http"
endpoint = "https://my_endpoint/api/v1/healthy?system_only=true"
interval = 60
headers = { "Authorization" = "Bearer..." }

[checks.id2]
pretty_name = "120s redis tcp check"
type = "tcp"
endpoint = "my_tcp_endpoint:9123"
secured = true
interval = 120
```

- [ ] TLS TCP
- [ ] TCP raw
- [ ] HTTP(S)
