### ISSUE TITLE
[MVP] Broker

### ISSUE THREAD

**Issue by alexandrebrg** [isok-io/isok#21]
## Broker

```toml
# Kafka brokers
brokers = []
topic = ""

[authentication]
type = "sasl"
username = ""
password = ""
```
